# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b11b7d4048bc7cc8a0c2e1e5574491d08086a4c7717cac66e91d013892320e3ddcc03d3fe3f684a987537e4caf26c51a837d04a56cb4e1dcaf9f09dd234b512f

test:
  secret_key_base: 9f8427981d36d3191790aec19938290a7162f8152ed43efc4ff21c0228a7e85ac82303ea908bbc43647575aaff094eab2f103c420bb5e7902a3a8fe5a828accf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
